export const BRAND_NAME = 'Web Tin Hoc'
export const OG_TITLE = 'ViecLamUIT: Nơi tìm việc cho dân IT'
export const RECAPTCHA_PUBLIC_KEY = process.env.NEXT_PUBLIC_RECAPTCHA_PUBLIC_KEY
export const SITE_BASE_URL = process.env.NEXT_PUBLIC_SITE_BASE_URL
export const DJANGO_BASE_URL = process.env.NEXT_PUBLIC_DJANGO_BASE_URL
export const STATIC_URL = process.env.NEXT_PUBLIC_STATIC_URL
export const MEDIA_URL = process.env.NEXT_PUBLIC_MEDIA_URL
export const DEBUG = process.env.NEXT_PUBLIC_DEBUG
export const DEFAULT_AVATAR = '/images/avatar-default.png'
export const AUTH_TOKEN = process.env.NEXT_PUBLIC_AUTH_TOKEN
export const AUTH_TOKEN_GUEST = process.env.NEXT_PUBLIC_AUTH_TOKEN_GUEST
export const DJANGO_BASE_WS = process.env.NEXT_PUBLIC_DJANGO_BASE_WS
export const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID
export const GOOGLE_SECRET_KEY = process.env.NEXT_PUBLIC_GOOGLE_SECRET_KEY
